@localhost=localhost:4004/odata/v4/main
@id=8c7cc309-8435-4534-b664-bc6c755e5065
@customerId=7bc3098e-1364-4721-8f41-99c77af37a9a
# Product ID sem estoque
@productId1=63688157-13ce-485b-82d2-6aaffa9300be
@productId2=33970049-ce41-46e7-8bac-32b4f354cddf

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

{
    "id": "{{id}}",
    "customer_Id": "{{customerId}}",
    "items": [
        {
            "Id": "c437a6bb-893e-4757-a854-de3d44521d14",
            "header": "{{id}}",
            "product": "{{productId1}}",
            "quantity": 10,
            "price": 1000
        },
        {
            "Id": "7fc59a33-dbc2-45d7-8f1f-85a292a7bc06",
            "header": "{{id}}",
            "product": "{{productId2}}",
            "quantity": 5,
            "price": 5000
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id=1234)
Content-Type: application/json
Authorization: Basic nino:Inicial@12345

###

PUT http://{{localhost}}/SalesOrderHeaders(id=1234)
Content-Type: application/json
Authorization: Basic nino:Inicial@12345
{
    "modifiedBy": "teste"
}


###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2332241572236.75
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 2332241572236.75
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer
Content-Type: application/json
Authorization: Basic edu:Inicial@12345


###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2332241572236.75&$expand=items($expand=product),customer
Content-Type: application/json
Authorization: Basic edu:Inicial@12345


###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2332241572236.75&$expand=items($expand=product;$filter=quantity le 39),customer
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

GET http://{{localhost}}/SalesOrderHeaders?$select=customer&$expand=customer($select=email)
Content-Type: application/json
Authorization: Basic edu:Inicial@12345


###

# Descobrindo a quantidade de registros

GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

# Descobrindo a quantidade de registros

GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

# Paginando os registros - pág 1

GET http://{{localhost}}/SalesOrderHeaders?$skip=0&$top=5
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

# Paginando os registros - pág 2

GET http://{{localhost}}/SalesOrderHeaders?$skip=5&$top=5
Content-Type: application/json
Authorization: Basic edu:Inicial@12345

###

# Buscando dados com $search

GET http://{{localhost}}/SalesOrderHeaders?$search=9o3k9
Content-Type: application/json
Authorization: Basic edu:Inicial@12345