@localhost=localhost:4004/odata/v4/main


GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id=1234)
Content-Type: application/json


###

PUT http://{{localhost}}/SalesOrderHeaders(id=1234)
Content-Type: application/json

{
    "modifiedBy": "teste"
}